#!/bin/sh
mydir=$(cd $(dirname $0) && echo $PWD)
export PC=pli

#
# Put my fake clang/clang++ compilers up front
#
export PATH="${mydir}":${PATH}
mkdir -p build
cd build
cmake -D CMAKE_PLI_COMPILER=${PC}  .. && cmake --build .
