#!/bin/env bash

# Simple front end to compile PL/I code
# Requires 'bash' for extended 'type' command

#set -x
mydir=$(cd $(dirname $0) && echo $PWD)

allpli=$(type -ap pli)
realpli=$(echo "${allpli}" | tail -1)

if [ "${realpli}x" = "x" ]; then
  echo "Unable to find the underlying PL/I compiler 'pli'" >&2
  exit 16
fi

if [ "${realpli}" = "${mydir}/pli" ]; then
  echo "Need to ensure the underlying PL/I compiler 'pli' is in your PATH" >&2
  exit 16
fi

# msf - rudimentary to get going
pliopts=""
version=false
for opt in $@; do
  opttext="${opt#-*}";
  if [ "${opttext}" = "${opt}" ]; then
    src="${opt}"
  else
    if [ "${opttext}" = 'M' ]; then
      pliopts="${pliopts} -c -qxinfo=dep -qnc"
    else 
      if [ "${opttext}" = 'v' ]; then
        version=true
      else
        pliopts="${pliopts} -${opttext}"
      fi
    fi
  fi
done

export STEPLIB=FULTONM.PORT.TEMPV6R2:$STEPLIB
if ${version} ; then
  (cd /tmp; echo " PLIVER: PROC OPTIONS(MAIN);" >$$.pli;  pli -qlist -qnc -c $$.pli >/dev/null 2>/dev/null ; cat $$.lst | head -1; rm $$.lst $$.pli)
fi
  
if [ "${src}x" = "x" ]; then
  if ! ${version}; then
    echo "Unable to determine source file from command line $@" >&2
    exit 8
  fi
fi

"${realpli}" ${pliopts} $src
