#!/bin/env bash

# Simple front end to compile PL/I code
# Requires 'bash' for extended 'type' command

#set -x
mydir=$(cd $(dirname $0) && echo $PWD)

allpli=$(type -ap pli)
realpli=$(echo "${allpli}" | tail -1)

if [ "${realpli}x" = "x" ]; then
  echo "Unable to find the underlying PL/I compiler 'pli'" >&2
  exit 16
fi

if [ "${realpli}" = "${mydir}/pli" ]; then
  echo "Need to ensure the underlying PL/I compiler 'pli' is in your PATH" >&2
  exit 16
fi

# msf - rudimentary to get going
pliopts="-qrent"
version=false
objparm=false
componly=false
objfile=''
src=''
for opt in $@; do
  opttext="${opt#-*}";
  if [ "${opttext}" = "${opt}" ]; then
    if ${objparm}; then
      objfile="${opttext}"
      objparm=false
    else
      if [ "${src}x" = "x" ]; then
        src="${opt}"
      else 
        src="${src} ${opt}"
      fi
    fi
  else
    objparm=false
    if [ "${opttext}" = 'M' ]; then
      pliopts="${pliopts} -c -qxinfo=dep -qnc"
    else 
      if [ "${opttext}" = 'v' ]; then
        version=true
      else 
        if [ "${opttext}" = 'o' ]; then
          objparm=true
        else
          if [ "${opttext}" = 'c' ]; then
            componly=true
            pliopts="${pliopts} -${opttext}"
          else
            pliopts="${pliopts} -${opttext}"
          fi
        fi
      fi
    fi
  fi
done

export STEPLIB=FULTONM.PORT.TEMPFE:FULTONM.PORT.TEMPBE:$STEPLIB
if ${version} ; then
  (cd /tmp; echo " PLIVER: PROC OPTIONS(MAIN);" >$$.pli;  pli -qlist -qnc -c $$.pli >/dev/null 2>/dev/null ; cat $$.lst | head -1; rm $$.lst $$.pli)
fi
  
if [ "${src}x" = "x" ]; then
  if ! ${version}; then
    echo "Unable to determine source file from command line $@" >&2
    exit 8
  fi
fi


#
# unfortunate restriction: to add 'support' for -c -o <object> we first write it to the local 
# directory and then move it to the right target location
# this doesn't work in general because the local directory may be read-only (among other issues)
#
# This code does not handle anything fancy like -c -o <object-directory> if there are multiple
# .o's being generated

fromobj=''
toobj=''
if [ "${objfile}x" != "x" ]; then
  if ${componly} ; then
    firstsrc=${src%% *}
    if [ "${firstsrc}" != "${src}" ]; then
      echo "No support for multiple source files being compiled with -c and -o option" >&2
      exit 8
    fi
    srcwithoutextension=${src%.*}
    fromobj="${srcwithoutextension}.o"
    toobj="${objfile}"
  else
    pliopts="${pliopts} -o ${objfile}"
  fi
fi

"${realpli}" ${pliopts} $src
rc=$?
if [ $rc -lt 4 ]; then
  if [ -f "${fromobj}" ]; then
    if [ "${fromobj}" != "${toobj}" ]; then
      mv "${fromobj}" "${toobj}" 
    fi
    rc=$?
  fi
fi
exit $rc
