#!/bin/sh
#********************************************************************
# Copyright (c) 2021 IBM
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#*********************************************************************
#set -x

CFLAGS="DLL,LONGNAME,RENT,SSCOM,CSECT,FLAG(I),WARN64,LANGLVL(EXTENDED),SUPPRESS(CCN3764),GONUMBER,OPT(2)"
ASMFLAGS="-mNOBATCH,GOFF,RENT,FLAG(0,ALIGN,CONT,NOIMPLEN,PUSH,RECORD,USING0,EXLITW)"
LKFLAGS="AC=1,EXTATTR=APF,DLL,DYNAM=DLL,CASE=MIXED,TERM"

INITDIR=$PWD

#
# Compile, assemble, link, run the 64-bit executable testcase
#
mkdir -p ../bin/64
cd ../bin/64
rm -f *.o *.lst svc99basic

INCDIR=`(cd ../../src; echo $PWD)`
SRCDIR=`(cd ../../src; echo $PWD)`
TSTDIR=`(cd ../../test/svc99; echo $PWD)`
xlc -c -I${INCDIR} -Wc,"${CFLAGS},LP64" ${TSTDIR}/svc99basic.c ${SRCDIR}/svc99c.c ${SRCDIR}/call31.c 
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

MACDIR=`(cd ../../src/maclib; echo $PWD)`
for f in ${SRCDIR}/call31a.s ${SRCDIR}/svc99msg.s; do
	obj=$(basename $f)
	obj=${obj%%.*}.o 
	as -o${obj} -I${MACDIR} "${ASMFLAGS},SYSPARM(AMODE64)" "${f}"
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi
done

xlc -Wl,"${LKFLAGS},LP64" -osvc99basic *.o
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

./svc99basic
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

echo "64-bit Test Passed"

# Go back to starting directory

cd ${INITDIR}

#
# --- do it all again for 31-bit ---
#

# Compile, assemble and link the 31-bit executable testcase
mkdir -p ../bin/31
cd ../bin/31
rm -f *.o *.lst svc99basic

xlc -c -I${INCDIR} -Wc,"${CFLAGS}" ${TSTDIR}/svc99basic.c ${SRCDIR}/svc99c.c ${SRCDIR}/call31.c 
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

INCDIR=`(cd ../../src/maclib; echo $PWD)`
for f in ${SRCDIR}/call31a.s ${SRCDIR}/svc99msg.s; do
	obj=$(basename $f)
	obj=${obj%%.*}.o
	as -o${obj} -I${MACDIR} "${ASMFLAGS},SYSPARM(AMODE64)" "${f}"
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi
done

xlc -Wl,"${LKFLAGS}" -osvc99basic *.o
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

./svc99basic
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

echo "31-bit Test Passed"
