#!/bin/sh
export CC=clang
export CC=clang++
mydir=$(cd $(dirname $0) && echo $PWD)

#
# Put my fake clang/clang++ compilers up front
#
export PATH="${mydir}":${PATH}
mkdir -p build
cd build
cmake -D CMAKE_C_COMPILER=${CC} -D CMAKE_CXX_COMPILER=${CXX} .. && cmake --build .
