#!/bin/sh
#
# e2ame : convert myself from ascii to ebcdic
# To convert a directory tree: find  . -type f -exec a2eme {} \;
#
if [ $# -ne 1 ]; then
  echo "syntax: $0 <file> : convert <file> from ebcdic to ascii" >&2
  exit 4
fi
me=$1

tmp=$TMPDIR/e2a.$$

if ! e2a <"${me}" >"${tmp}" ; then
  echo "conversion failed" >&2
  exit 4
fi

if ! mv "${tmp}" "${me}"; then
  echo "unable to move temporary file to ${me}. file not updated" >&2
  rm "${tmp}"
  exit 4
fi

