#include <stdio.h>
#include <errno.h>

#pragma pack(full)
struct DCollectHeader {
	unsigned short dculeng;
	int:16;

	unsigned char dcurctyp[2];
	unsigned short dcuvers;

	unsigned int dcusysid;
	char dcutmstp[8];
	int:32;
}; 

struct VolRec {
	struct DCollectHeader hdr;
	char dcvvolsr[6];

	int:6;
	int dcvphyst:2;

	int dcvevlcp:1;
	int dcvebytk:1;
	int dcvelspc:1;
	int:5;

	int:24;
	unsigned char dcvperct;

	unsigned int dcvfresp;
	unsigned int dcvalloc;
	unsigned int dcvvlcap;
	char dcvdetails[28];

	unsigned short dcvdvnum;
	int:16;

	unsigned short dcvsglng;
	char dcvsgtcl[30]; 

	char dcvdptyp[8];
	
	char dcvmoredetails[28];

	unsigned int dcvfcyls;
	unsigned int dcvftrks;

	int:32; 
};
#pragma pack(pop)

	
int main(int argc, char* argv[]) { 
	FILE* fp;
	struct VolRec volrec;
	int rc;
	int tc;
	int vc;

	if (argc != 2) {
		fprintf(stderr, "Syntax: %s <dataset>\n");
		fprintf(stderr, "  where <dataset> is the data set generated by DCOLLECT that contains volume information\n");
		exit(16);
	}
	if (sizeof(struct VolRec) != 160) {
		fprintf(stderr, "VolRec should be 160 bytes but is %d bytes\n", sizeof(struct VolRec));
		exit(16);
	}

	fp = fopen(argv[1], "rb,type=record");
	if (!fp) {
		perror("Unable to open DCOLLECT file for read");
		exit(16);
	}

	tc=0;
	vc=0;
	while ((rc = fread(&volrec, sizeof(volrec), 1, fp)) > 0) {
		++tc;
		if (volrec.hdr.dcurctyp[0] == 'V') { 
			++vc;
		}
	}
	printf("read %d records. read %d volume records\n", tc, vc);
	return 0;
}
