#!/bin/sh
#set -x
# 
# Determine what 'xx' is and print it out
# for a variety of things.
# This code is a quick hack - should be refactored
#
me=$0
if [ $# -lt 1 ]; then
  echo "Syntax: $me <what>\n" >&2
  echo "  where <what> is the member you want to determine XX for\n" >&2
  echo "<what> can be:\n" >&2
  echo "LOAD ........ SYS0.IPLPARM(LOADxx) member at IPL\n" >&2
  echo "IEASYS ...... PARMLIB Concatenation(IEASYSxx) member\n" >&2
  echo "IEASYM ...... PARMLIB Concatenation(IEASYMxx) member\n" >&2
  echo "SMFPRM ...... PARMLIB Concatenation(SMFPRMxx) member\n" >&2
  exit 4
fi

what=$(echo $1 | tr '[:lower:]' '[:upper:]')
if [ "${what}" = "LOAD" ]; then
  zinfo -t ipl | grep 'ipaloadxx:' | awk ' { print $2 }' | tr -d "'" 
  exit 0
elif [ "${what}" = "IEASYS" ] || [ "${what}" = "IEASYM" ]; then
  #
  # Theoretically, need to check each of COMMNDxx, IEACMDxx, and LOADxx but 
  # will do a partial implementation here and just look in LOADxx for 
  # a SET SMF=xx. If not present, return 00
  # Also note that the format can be more complex and be multiple xx's, e.g
  # SET SMF=(00,01,02,...,0n)
  # and it could also have an L for listing in it.
  # For now, error out if this is encountered.
  if ! load=$(${me} LOAD); then
    echo "Unable to determine LOADxx dataset" >&2
    exit 8
  fi
  keyword="${what}"
  if [ "${keyword}" = "IEASYS" ]; then
    keyword="SYSPARM"
  fi
  entry=$(cat "//'SYS0.IPLPARM(LOAD${load})'" | egrep ^${keyword})
  if [ $? -gt 0 ]; then
    echo "00"
  else
    entries=$(echo "${entry}" | wc -w)
    if [ ${entries} -ne 2 ]; then
      echo "Unexpected entry for ${entry}" >&2
      exit 8
    fi
    xx=$(echo "${entry}" | awk '{print $2; }')
    length=$(echo "${xx}" | wc -c)
    if [ ${length} -ne 3 ]; then
      echo "Unexpected entry for ${keyword} ${xx}. Expected ${xx} to be exactly 2 characters" >&2
      exit 8
    fi
    echo ${xx}
  fi
elif [ "${what}" = "SMFPRM" ]; then
  #
  # Look for SMF=xx keyword in IEASYSxx
  #
  if ! xx=$(${me} IEASYS); then
    echo "Unable to determine IEASYSxx dataset" >&2
    exit 8
  fi
  if ! pdd=$(parmwhence "IEASYS${xx}"); then
    echo "Unable to determine PARMLIB dataset concatenation for IEASYS${xx}\n" >&2
    exit 8
  fi
  xx=$(cat "//'${pdd}(IEASYS${xx})'" | grep 'SMF=' | tr '=,' '  ' | awk ' { print $2; }')
  length=$(echo "${xx}" | wc -c)
  if [ ${length} -ne 3 ]; then
    echo "Unexpected entry for ${keyword} ${xx}. Expected ${xx} to be exactly 2 characters" >&2
    exit 8
  fi
  echo ${xx}
fi
